import type { Metadata } from "next";
import ClientLocalizationProvider from "@/components/provider/date/ClientLocalizationProvider";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
			// className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<ClientLocalizationProvider>
					{children}
				</ClientLocalizationProvider>
			</body>
		</html>
	);
}
